### ISSUE TITLE
git clone instructions refer to incorrect repo

### ISSUE THREAD

**Issue by xpufx** [dapperfu/openai-notebooks#1]
git clone https://github.com/username/openai-notebooks.git

username should be replaced with dapperfu

**Comment by dapperfu** [comment]
I had ChatGPT update the read me.

**Comment by xpufx** [comment]
:) What was the prompt?

**Comment by dapperfu** [comment]
There were a few. See also the joke at the bottom of the README. 😁

**Comment by dapperfu** [comment]
ChatGPT had issues yesterday so I don't have my history. Paraphrasing: 

1. Write a 2 sentence disclaimer for a GitHub README.md that most of the repository is a work in progress but most things have been generated from Chat GPT.
2. Create a GitHub README.md for a repository with the description "Personal ChatGPT exploration in Jupyter Notebooks" . The README.md shall use "https://github.com/dapperfu/openai-notebooks.git" as the clone URL.
3. Create 3 additional example notebooks. One example shall be about image generation.
4. Create 3 paragraphs for a GitHub README.md explaining that the repository is primarily ChatGPT generated.
5. Rewrite this joke "<joke>" where the the retired engineer uses ChatGPT instead of a hammer.

**Comment by xpufx** [comment]
Ahah. I had started reading from the end of the readme and thought the repo was defaced for a minute. Good stuff.
